include:
 - remote: 'https://gitlab.com/neuvector/gitlab-plugin/-/raw/master/scan.yml'

stages:
  - integrate
  - package
  - scan
  # - deploy

variables:
  # defined in GitLab project configuration (Settings > CI/CD > Variables)
  # CONTAINER_REGISTRY_PASSWD
  # CONTAINER_REGISTRY_USER
  # CONTAINER_REGISTRY_DOMAIN
  # CONTAINER_REGISTRY_FOLDER
  # container information
  CONTAINER_REPOSITORY: "$CONTAINER_REGISTRY_DOMAIN/$CONTAINER_REGISTRY_FOLDER/ecorp-backend-demo"
  CONTAINER_APP_VERSION: "1.0.$CI_PIPELINE_ID"

code-quality:
  image: mcr.microsoft.com/dotnet/sdk:6.0
  stage: integrate
  before_script:
    # dotnet cli tools
    - dotnet tool install -g dotnet-format --version "6.*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json
    - export PATH="$PATH:/root/.dotnet/tools"
  script:
    # lint
    - dotnet-format --verify-no-changes --severity warn --verbosity:diagnostic
    # build
    - dotnet restore
    - dotnet build --no-restore --configuration Debug
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
      allow_failure: true

container-image:
  image:
    name: quay.io/containers/podman
  stage: package
  script:
    - podman build --format docker -f src/WebApi/Dockerfile -t $CONTAINER_REPOSITORY:$CONTAINER_APP_VERSION .
    - podman login -u $CONTAINER_REGISTRY_USER -p $CONTAINER_REGISTRY_PASSWD $CONTAINER_REGISTRY_DOMAIN
    - podman push $CONTAINER_REPOSITORY:$CONTAINER_APP_VERSION
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always

neuvector_scan:
  variables:
    # image_registry_url: "https://registry.hub.docker.com"
    image_registry_url: $CONTAINER_REGISTRY_DOMAIN
    image_registry_user: $CONTAINER_REGISTRY_USER
    image_registry_password: $CONTAINER_REGISTRY_PASSWD
    image_repo: $CONTAINER_REGISTRY_FOLDER/ecorp-backend-demo
    image_tag: $CONTAINER_APP_VERSION
    nv_registry_user: $CONTAINER_REGISTRY_USER
    nv_registry_password: $CONTAINER_REGISTRY_PASSWD
    scan_layers: "false"
    high_vul_to_fail: 5
    medium_vul_to_fail: 9
    vul_names_to_fail: "CVE-2020-1971, CVE-2020-1972"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
